### ISSUE TITLE
Swift 2.0 - Xcode 7 support

### ISSUE THREAD

**Issue by bcamur** [flightonary/Moscapsule#13]
There are some issues about unavailable methods. Specificially: 
"'advance' is unavailable: call the 'advancedBy(n)' method on the index"
in the Moscapsule.swift file

**Comment by ammoqq** [comment]
same issue here with swift 1.2 xcode 6.3

**Comment by flightonary** [comment]
I deleted the code causes the problem.

**Comment by iameve** [comment]
It seems it has another error now

**Comment by LightD** [comment]
I believe this is resolved and can be closed
