### ISSUE TITLE
How to use willMessage using Moscapsule?

### ISSUE THREAD

**Issue by ppsdang** [flightonary/Moscapsule#14]
How to use willMessage using Moscapsule. I am unable to find any method related to will message.

**Comment by hankbao** [comment]
You can use mqttWillOpts in MQTTConfig.

**Comment by ppsdang** [comment]
Thanks,

It is working. Your help much appreciated.



On Wed, Oct 21, 2015 at 10:00 AM, Hank BAO <notifications@github.com> wrote:

> You can use mqttWillOpts in MQTTConfig.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flightonary/Moscapsule/issues/14#issuecomment-149779194>
> .
>



-- 
[image: Oodles Technologies Pvt Ltd] <http://www.oodlestechnologies.com/>

Pawanpreet Singh  Assistant Consultant Development, Oodles Technologies Pvt
Ltd
Phone:   +91 124 4368 395
Mobile:   +91 9711588672 <+919711588672>
Email:     pawanpreet.singh@oodlestechnologies.com
Website:  http://www.oodlestechnologies.com/
Skype:     ppsdang
Address: Unit No 951-955 , Tower B1, Spaze I-Tech Park , Sector 49 , Sohna
Road , Gurgaon , India , 122001
[image: Twitter] <https://twitter.com/oodlestech> [image: Facebook]
<https://www.facebook.com/OodlesTech> [image: Google +]
<https://plus.google.com/+Oodlestechnologies/posts> [image: LinkedIn]
<https://www.linkedin.com/company/oodles-technologies-pvt-ltd>

This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Oodles
Technologies is not responsible for errors or omissions in this message and
denies any responsibility for any damage arising from the use of e-mail.
Any opinion and other statement contained in this message and any
attachment are solely those of the author and do not necessarily represent
those of the company

**Comment by hankbao** [comment]
@ppsdang you may close this issue if it's solved.
