### ISSUE TITLE
Definition of Queue Name

### ISSUE THREAD

**Issue by nardoguy14** [flightonary/Moscapsule#26]
Hello, so I realize if i set the client Id to a certain value, it is used within the queue name on the broker such as

Queue mqtt-subscription-{name here}qos1

Where does this get set within the code? Id like to be able to define my own queue names.

**Comment by flightonary** [comment]
Would you tell me what kind of queue?
Is it serialQueue in class MQTTClient?

**Comment by flightonary** [comment]
done
