### ISSUE TITLE
Why do you not use another queue for library? 

### ISSUE THREAD

**Issue by AlexIzh** [flightonary/Moscapsule#41]
You have `serialQueue` in the your code and method `addRequestToQueue`. But `serialQueue` isn't used anywhere and method `addRequestToQueue` calls closure in the current queue and doesn't use `serialQueue`. Why? I have a lot of issues because it. Did you do it because some special issue or not? If not, I can create pull request with this

**Comment by flightonary** [comment]
Oh... sorrry. this is my stupid mistake.
I corrected this issue.
