### ISSUE TITLE
Compiler Error: 'openssl/ssl.h' file not found

### ISSUE THREAD

**Issue by rgruskin** [flightonary/Moscapsule#67]
Running Xcode 8.2.1 and getting following compiler error:
IOS/MyApp/Moscapsule/mosquitto/lib/mosquitto_internal.h:27:12: 'openssl/ssl.h' file not found when I try to build the Mocapsule error 

Any ideas why?  I don't see the file ssl.h.

**Comment by rgruskin** [comment]
Follow up with more information.  I am installing manual without CocoaPods

An answer would be greatly appreciated.

**Comment by flightonary** [comment]
It was solved now.

**Comment by sultan2Dilawar** [comment]
> It was solved now.

how did you fix it ?

**Comment by chikiball** [comment]
I fixed this issue by adding project 'MyApp.xcodeproj' line in the podfile, I previously missed this line.
