### ISSUE TITLE
Create a CocoaPods Distro

### ISSUE THREAD

**Issue by jsloyer** [flightonary/Moscapsule#9]
This an awesome library and it would be great to have a CocoaPods distro to make installation easier.

https://guides.cocoapods.org/making/making-a-cocoapod.html

**Comment by guglielmino** [comment]
+1

**Comment by braitom** [comment]
+1

**Comment by bago2k4** [comment]
+1

**Comment by thepug** [comment]
+1

**Comment by flightonary** [comment]
I appended a podspec file to the repository. Please see Installation in the readme.
